version: '3.9'
services:
  scout:
    image: ghcr.io/shba007/unwork-scout:latest
    env_file:
      - .env.prod
    ports:
      - 2400:3000
    networks:
      - front-tier
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  browserless:
    image: ghcr.io/browserless/chromium:latest
    restart: on-failure:3
    ports:
      - 1200:3000
    networks:
      - front-tier

  postgres:
    image: postgres:17-alpine
    command: '-d 1'
    env_file:
      - .env.prod
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 1000:5432
    networks:
      - front-tier
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  front-tier:
    driver: overlay
