version: '3.9'
services:
  scout:
    image: 'ghcr.io/shba007/unwork-scout:latest'
    env_file:
      - .env.prod
    ports:
      - 2400:3000
    networks:
      - front-tier
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  front-tier:
    driver: overlay
